on:
  push:
    tags:
      - "swarm-language-vscode-*"

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 20
      - run: |
          cd editors/vscode           && \
          npm update                  && \
          npm clean-install           && \
          cd client                   && \
          npm update                  && \
          npm clean-install           && \
          cd ..                       && \
          npm run gen-syntax          && \
          npm run build
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          packagePath: editors/vscode
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          packagePath: editors/vscode
          pat: ${{ secrets.VSX_MARKETPLACE_TOKEN }}
