# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: VSCode CI

on:
  push:
    paths:
      - 'editors/vscode/**'
      - .github/workflows/vscode*
    branches:
      - '*'
  pull_request:
    paths:
      - .github/workflows/vscode*
      - 'editors/vscode/**'
    branches:
      - '*'

jobs:
  build:
    name: VSCode build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd editors/vscode           && \
        npm update                  && \
        npm clean-install           && \
        cd client                   && \
        npm update                  && \
        npm clean-install           && \
        tsc --build .               && \
        cd ..                       && \
        npm clean-install           && \
        npm run build --if-present
    - run: |
        cd editors/vscode
        npm test
